### ISSUE TITLE
Problem with DaOnes Vanilla++ Mod

### ISSUE THREAD

**Issue by cdiehr** [cf-tools/omega-scripts#1]
I've tried a lot to get your Mod installed within DaOnes Mod, but I failed.
Can you help?
https://github.com/Da0ne/DZMods

**Comment by philippj** [comment]
Can you go in a bit more detail? What does not work and under which circumstances.

**Comment by cdiehr** [comment]
I don't know where to put the code.
I tried many variants but noting worked.

**Comment by evansalles** [comment]
I'm with the same issue here. I was trying to use Vanilla++ and AirDrop by mov3ax but his mod is no longer  supported. I'm trying do find an airdrop mod, but with Vanilla++ it is hard to us noobs to install it hehe.
Vanilla++ use a customized init.c, so we get confused trying to make it work.

Here is their code:
init.c
https://github.com/Da0ne/DZMods/blob/master/mpmissions/DayZSurvival.chernarusplus/init.c
DayZSurvival.c
https://github.com/Da0ne/DZMods/blob/master/mpmissions/DayZSurvival.chernarusplus/ScriptedMods/Modules/ServerMission/DayZSurvival.c

**Comment by lonewolfss** [comment]
no longer works i just get a error saying its missing ; on  line 674

**Comment by philippj** [comment]
When using the DayZSurvival mission you just need to follow the installation guide but use the init.c found inside the DayZSurvival folder.
