### ISSUE TITLE
Hey mate 

### ISSUE THREAD

**Issue by Whocares131** [cf-tools/omega-scripts#3]
it doesnt work for me
dunno what the problem is

thats my init

can you show me yours please would be really cool.

[init.zip](https://github.com/cf-tools/omega-scripts/files/2583052/init.zip)

**Comment by Moondarker** [comment]
Your init.c seems fine (I've even tested it inside a mission)
Make sure that you have _passwordAdmin_ option set in server config and you're actually logging in as an admin (**#login** _[pwd]_ in chat) before executing any commands

**Comment by Whocares131** [comment]
Ok i will try that later, was not logged in as an Admin. Thanks Mate.
