### ISSUE TITLE
HELP with VANILLA ++

### ISSUE THREAD

**Issue by LArtDesChOiX** [cf-tools/omega-scripts#8]
Hi friend.

I did not manage to start the "mod" on a Vanilla ++ "constructor": (....

I need to add his:

ref BetterAirdrop Airdrop;
     void DayZSurvival ()
         Airdrop = new BetterAirdrop ();

At the beginning of the "custom mission" not ???

I try several things; .. not successful. THANK YOU

**Comment by LArtDesChOiX** [comment]
class DayZSurvival : MissionServer
{
	ref BetterAirdrop Airdrop;
        void DayZSurvival ()
        Airdrop = new BetterAirdrop ();

        private ref set<ref VPPModuleManager> m_Modules;
	ref InfectedHordes m_ZombieEvents;
	protected float m_LogInTimerLength = 5;     //The timer for players who join the server  (in seconds)
	protected int   m_UseSpawnMenu = GetGame().ServerConfigGetInt("SpawnSelectionMenu");
	bool m_StaminaStatus = false;


I do that... Don't work ?

**Comment by LArtDesChOiX** [comment]
HELP me please :/

**Comment by LArtDesChOiX** [comment]
@philippj ?

**Comment by sy8282** [comment]
Vanilla++ is da0nes mod I'd ask for help on his github they are quick to respond to issues

**Comment by philippj** [comment]
I don't know how Vanilla++ works, so please do as Sy suggested.
